const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const results=[];let s=await setup();try{
 await s.page.addInitScript(()=>{const native=window.setInterval;window.setInterval=function(fn,ms,...args){if(ms===60)return 0;return native(fn,ms,...args)}});await s.page.goto(s.origin+'/pages/index.html',{waitUntil:'domcontentloaded'});await s.page.waitForFunction(()=>HomeStartup.phase==='ready',{},{timeout:8500});const result=await s.page.evaluate(()=>({elapsed:HomeStartup.releasedAt-HomeStartup.startedAt,forced:HomeStartup.forced,releases:HomeStartup.releases,cleanups:loaderCleanups.length}));assert.equal(result.forced,true);assert.ok(result.elapsed>=7900&&result.elapsed<8200);assert.equal(result.releases,1);assert.equal(result.cleanups,0);assert.equal(await s.page.locator('.home-cta-btn').evaluate(e=>getComputedStyle(e.closest('.home-enter-item')).opacity),'1');assert.deepEqual(s.errors,[]);results.push({case:'real 8s watchdog when ordinary tick unavailable',pass:true,result})
 }finally{await s.close()}
 s=await setup();try{await s.page.route('**/home-scene/v4/*',()=>new Promise(()=>{}));await s.page.goto(s.origin+'/pages/index.html',{waitUntil:'domcontentloaded'});await s.page.evaluate(()=>{const actual=Date.now;Date.now=()=>HomeStartup.overlayDeadline+10;document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));Date.now=actual;HomeStartup.complete(false)});assert.equal(await s.page.locator('#home-loading-screen').count(),0);assert.equal(await s.page.evaluate(()=>HomeStartup.releases),1);assert.equal(await s.page.evaluate(()=>loaderCleanups.length),0);results.push({case:'controlled absolute deadline on visibility/pageshow; late completion idempotent',pass:true})}finally{await s.close()}
 s=await setup({token:true});try{await s.page.addInitScript(()=>{sessionStorage.setItem('lxm_home_loader_done','1');const native=Storage.prototype.removeItem;Storage.prototype.removeItem=function(key){if(key==='lxm_home_loader_done')throw Error('controlled clearToken marker removal');return native.call(this,key)}});await s.page.goto(s.origin+'/pages/index.html');await s.page.evaluate(()=>clearToken());assert.equal(await s.page.evaluate(()=>HomeStartup.auth().token),null);assert.equal(await s.page.locator('#home-loading-screen').count(),0);assert.deepEqual(s.errors,[]);results.push({case:'Session removeItem fault in actual clearToken branch',pass:true})}finally{await s.close()}
 for(const op of ['setItem','removeItem']){s=await setup({token:true});try{await s.page.addInitScript(op=>{sessionStorage.setItem('lxm_home_loader_done','1');const native=Storage.prototype[op];Storage.prototype[op]=function(key,...args){if(key==='token')throw Error('controlled auth write/removal');return native.call(this,key,...args)}},op);await s.page.goto(s.origin+'/pages/index.html');if(op==='setItem'){await s.page.evaluate(()=>saveToken('fixture-memory-session'));assert.equal(await s.page.evaluate(()=>HomeStartup.auth().token==='fixture-memory-session'),true)}else{await s.page.evaluate(()=>clearToken());assert.equal(await s.page.evaluate(()=>HomeStartup.auth().token),null)}assert.deepEqual(s.errors,[]);results.push({case:'explicit auth '+op+' failure retains valid in-memory outcome',pass:true})}finally{await s.close()}}
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m2/step-004-boundaries-results.json'),JSON.stringify({scope:'Actual homepage; real watchdog timing and controlled clock/storage fault paths',results},null,2)+'\n');console.log('PASS '+results.length+' startup deadline/storage boundaries')
})().catch(e=>{console.error(e);process.exitCode=1});
