const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const results=[];let s=await setup();try{
 await s.page.addInitScript(()=>{sessionStorage.setItem('lxm_home_loader_done','1');Math.random=()=>0});await s.page.goto(s.origin+'/pages/index.html');assert.equal(await s.page.evaluate(()=>!!HomeScene.motion),true,'scene must expose its owned motion effect');await s.page.waitForFunction(()=>HomeScene.motion.inspect().loaded.length===5);
 const first=await s.page.evaluate(()=>HomeScene.motion.inspect());await s.page.waitForTimeout(1100);const second=await s.page.evaluate(()=>({motion:HomeScene.motion.inspect(),breath:document.querySelector('.home-scene-breathe').style.transform,hair:document.querySelector('.home-scene-hair-side').style.transform,lamp:document.querySelector('.home-scene-lamp').style.opacity}));
 assert.notEqual(second.breath,'');assert.notEqual(second.hair,'');assert.ok(Number(second.lamp)>0);assert.ok(second.motion.environmentFrames>first.environmentFrames);
 await s.page.waitForFunction(()=>Number(document.querySelector('.home-scene-blink').style.opacity)>.1,{},{timeout:7500});await s.page.evaluate(()=>HomeScene.current.pause('test-hidden'));
 assert.equal(await s.page.locator('.home-scene-blink').evaluate(e=>Number(e.style.opacity)),0);assert.equal(await s.page.locator('.home-scene-gesture').evaluate(e=>e.style.transform),'none');
 const stopped=await s.page.evaluate(()=>HomeScene.motion.inspect());await s.page.waitForTimeout(450);assert.deepEqual(await s.page.evaluate(()=>HomeScene.motion.inspect()),stopped);await s.page.evaluate(()=>HomeScene.current.pause('test-hidden',false));
 await s.page.waitForFunction(()=>HomeScene.motion.inspect().idleCount>0,{},{timeout:16000});await s.page.screenshot({path:artifact('docs/design/home-redesign/execution/evidence/home-m3/step-008-motion.png')});assert.deepEqual(s.errors,[]);results.push({case:'seven motion classes, source-consistent layers, blink/idle pause cancellation',pass:true,metrics:await s.page.evaluate(()=>HomeScene.motion.inspect())});
 }finally{await s.close()}
 for(const failure of ['hair-side','blink','lamp','canvas']){s=await setup();try{
  await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));
  if(failure==='canvas')await s.page.addInitScript(()=>HTMLCanvasElement.prototype.getContext=function(){throw Error('controlled Canvas failure')});else await s.page.route(`**/*${failure==='hair-side'?'hair_side_physics':failure==='blink'?'blink_crop':'lamp_glow'}*.webp`,r=>r.abort());
  await s.page.goto(s.origin+'/pages/index.html');await s.page.waitForTimeout(250);assert.equal(await s.page.locator('.home-scene-character').evaluate(e=>e.naturalWidth>0&&!e.hidden),true);await s.page.locator("button[onclick=\"handleHomeQuickAction('more')\"]").click();await s.page.waitForSelector('#auth-login-modal.is-open');assert.deepEqual(s.errors,[]);results.push({case:'isolated '+failure+' failure with real login entry',pass:true})
 }finally{await s.close()}}
 s=await setup();try{await s.page.emulateMedia({reducedMotion:'reduce'});await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));await s.page.goto(s.origin+'/pages/index.html');await s.page.waitForTimeout(150);assert.equal(s.requests.filter(r=>/hair_|blink_crop|lamp_glow/.test(r.path)).length,0);assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);results.push({case:'initial reduced motion avoids optional downloads and loops',pass:true})}finally{await s.close()}
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m3/step-008-results.json'),JSON.stringify({scope:'Actual homepage desktop Chrome; source motion rules and controlled layer failures',results},null,2)+'\n');console.log('PASS '+results.length+' motion scenarios')
})().catch(e=>{console.error(e);process.exitCode=1});
