const assert=require('node:assert/strict'),fs=require('node:fs');
const {setup,artifact}=require('./home_browser_helpers.cjs');
async function start(token=true,configure=async()=>{}){const s=await setup({token});await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));await configure(s);await s.page.goto(s.origin+'/pages/index.html',{waitUntil:'domcontentloaded'});await s.page.waitForFunction(()=>window.HomeData);return s}
const note=(key)=>`[data-home-module="${key}"]`;
(async()=>{const results=[];
 let s=await start(false);try{await s.page.waitForFunction(()=>document.querySelector('[data-home-module="feedList"]').dataset.state==='success');assert.deepEqual(s.apiRequests.map(r=>r.path),['/api/feed/list?size=8']);assert.equal(await s.page.locator('#known-days').textContent(),'故事从今天开始');results.push({case:'visitor public Feed only',pass:true})}finally{await s.close()}
 s=await start(true,async s=>{await s.page.route('**/api/relationship/status',()=>new Promise(()=>{}))});try{
  await s.page.waitForFunction(()=>document.querySelector('[data-home-module="diary"]').dataset.state==='success');assert.equal(await s.page.locator('#diary-lock').getAttribute('data-lock-state'),'unknown');assert.equal(await s.page.locator('#relationship-level-name').textContent(),'—');
  assert.equal(s.apiRequests.length,5);assert.equal(await s.page.locator('#main-content').evaluate(e=>e.classList.contains('content-loaded')),true);
  await s.page.waitForFunction(()=>document.querySelector('[data-home-module="relationship"]').dataset.state==='error',{},{timeout:9000});assert.equal(await s.page.evaluate(()=>!!HomeStartup.auth().token),true);assert.equal(await s.page.locator('#diary-lock').getAttribute('data-lock-state'),'unknown');results.push({case:'independent diary/unknown lock and relationship timeout',pass:true})
 }finally{await s.close()}
 s=await start(true,async s=>{await s.page.route('**/api/**',()=>new Promise(()=>{}))});try{
  const failed=[];s.page.on('requestfailed',r=>{if(r.url().includes('/api/'))failed.push(new URL(r.url()).pathname)});
  await s.page.evaluate(()=>{loadPage();loadPage();loadFeedHomeCard();document.dispatchEvent(new Event('visibilitychange'))});
  await s.page.waitForFunction(()=>Object.values(getHomeDataController().inspect().modules).every(v=>v.status==='error'),{},{timeout:9000});
  assert.equal(failed.length,6);assert.equal(await s.page.evaluate(()=>getHomeDataController().inspect().batches),0);assert.equal(await s.page.evaluate(()=>!!HomeStartup.auth().token),true);assert.equal(await s.page.locator('#relationship-level-name').textContent(),'—');assert.equal(await s.page.locator(note('feedList')).getAttribute('data-state'),'error');results.push({case:'all six hung fetches cancelled at one 8s deadline; deduplication',pass:true})
 }finally{await s.close()}
 s=await start();try{
  await s.page.waitForFunction(()=>document.getElementById('relationship-level-name').textContent==='亲密');await s.page.waitForFunction(()=>getHomeDataController().inspect().batches===0);
  await s.page.route('**/api/relationship/status',r=>r.abort());await s.page.evaluate(()=>getHomeDataController().retry('relationship'));assert.equal(await s.page.locator('#relationship-level-name').textContent(),'亲密');assert.equal(await s.page.locator('#diary-lock').getAttribute('data-lock-state'),'unlocked');assert.match(await s.page.locator(note('relationship')).textContent(),/更新失败/);
  let retryCount=0;await s.page.route('**/api/relationship/status',async r=>{retryCount++;await new Promise(r=>setTimeout(r,150));await r.fulfill({json:{code:0,data:{level:0,level_name:'陌生',current_growth:0,next_threshold:200}}})});
  await s.page.evaluate(()=>{getHomeDataController().retry('relationship');getHomeDataController().retry('relationship')});await s.page.waitForFunction(()=>document.getElementById('relationship-level-name').textContent==='陌生');assert.equal(retryCount,1);assert.equal(await s.page.locator('#diary-lock').getAttribute('data-lock-state'),'locked');results.push({case:'known data retained on failure, bounded local retry deduped',pass:true});
  let held;await s.page.route('**/api/relationship/status',r=>{held=r});await s.page.evaluate(()=>{getHomeDataController().retry('relationship')});while(!held)await new Promise(r=>setTimeout(r,10));
  await s.page.unroute('**/api/relationship/status');await s.page.evaluate(()=>saveToken('fixture-new-account'));await s.page.evaluate(()=>loadPage());await s.page.waitForFunction(()=>getHomeDataController().inspect().batches===0);try{await held.fulfill({status:401,body:'{}'})}catch(_){}await s.page.waitForTimeout(100);assert.equal(await s.page.evaluate(()=>HomeStartup.auth().token==='fixture-new-account'),true);assert.equal(await s.page.locator('#relationship-level-name').textContent(),'亲密');results.push({case:'account switch cancels old request; late 401 cannot clear new context',pass:true});
  await s.page.route('**/api/relationship/status',r=>r.fulfill({status:401,body:'{}'}));await s.page.evaluate(()=>getHomeDataController().retry('relationship'));await s.page.waitForFunction(()=>homeAuthMode==='visitor');assert.equal(await s.page.evaluate(()=>HomeStartup.auth().token),null);assert.equal(await s.page.locator('#known-days').textContent(),'故事从今天开始');results.push({case:'current 401 clears private modules and downgrades visitor',pass:true});assert.deepEqual(s.errors,[])
 }finally{await s.close()}
 s=await start(true,async s=>{await s.page.addInitScript(()=>{const get=Storage.prototype.getItem;Storage.prototype.getItem=function(k){if(k==='token')throw Error('controlled unavailable token');return get.call(this,k)}})});try{await s.page.waitForFunction(()=>getHomeDataController().inspect().batches===0);assert.deepEqual(s.apiRequests.map(r=>r.path),['/api/feed/list?size=8']);assert.equal(await s.page.locator('#relationship-level-name').textContent(),'—');assert.equal(await s.page.locator(note('relationship')).getAttribute('data-state'),'unknown');assert.deepEqual(s.errors,[]);results.push({case:'unavailable auth read is unknown, never false visitor/Lv0',pass:true})}finally{await s.close()}
 s=await start(true,async s=>{await s.page.route('**/api/relationship/status',r=>r.fulfill({json:{code:0,data:{}}}))});try{await s.page.waitForFunction(()=>document.querySelector('[data-home-module=\"relationship\"]').dataset.state==='error');assert.equal(await s.page.locator('#relationship-level-name').textContent(),'—');assert.equal(await s.page.locator('#diary-lock').getAttribute('data-lock-state'),'unknown');results.push({case:'malformed success response is failure, never fabricated Lv0',pass:true})}finally{await s.close()}
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m2/step-006-results.json'),JSON.stringify({scope:'Actual homepage, desktop Chrome controlled business responses; real HTTP cancellation',results},null,2)+'\n');console.log('PASS '+results.length+' homepage data scenarios')
})().catch(e=>{console.error(e);process.exitCode=1});
