const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const s=await setup({token:true});try{
 await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));await s.page.goto(s.origin+'/pages/index.html');await s.page.waitForFunction(()=>HomeScene.current.running);const id=await s.page.evaluate(()=>HomeScene.current.id);
 await s.page.evaluate(()=>openLoginModal());await s.page.waitForSelector('#auth-login-modal.is-open');assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false,'Actual open login modal must suspend scene');
 await s.page.keyboard.press('Escape');await s.page.waitForFunction(()=>HomeScene.current.running);
 await s.page.evaluate(()=>{HomeScene.current.pause('test-hidden');openLoginModal()});await s.page.waitForFunction(()=>HomeScene.current.inspect().reasons.includes('login'));await s.page.evaluate(()=>{closeLoginModal();HomeScene.current.setMotionEnabled(false)});await s.page.waitForFunction(()=>!HomeScene.current.inspect().reasons.includes('login'));assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);await s.page.evaluate(()=>HomeScene.current.pause('test-hidden',false));assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);await s.page.evaluate(()=>HomeScene.current.setMotionEnabled(true));await s.page.waitForFunction(()=>HomeScene.current.running);
 await s.page.evaluate(()=>VoiceEntry.begin());await s.page.waitForSelector('.voice-entry:not([hidden])');await s.page.waitForFunction(()=>HomeScene.current.inspect().reasons.includes('voice'));assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);
 await s.page.locator('.voice-entry-close').click();await s.page.waitForFunction(()=>HomeScene.current.running);
 // The real voice DOM remains open through state changes; these two terminal labels are controlled, not a real call.
 await s.page.evaluate(()=>VoiceEntry.begin());await s.page.waitForSelector('.voice-entry:not([hidden])');await s.page.locator('.voice-entry h1').evaluate(e=>e.textContent='暂时无法接通');assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);await s.page.locator('.voice-entry h1').evaluate(e=>e.textContent='通话已结束');assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);await s.page.locator('.voice-entry-close').click();await s.page.waitForFunction(()=>HomeScene.current.running);
 for(let i=0;i<6;i++){await s.page.evaluate(()=>openLoginModal());await s.page.waitForFunction(()=>!HomeScene.current.running);await s.page.evaluate(()=>closeLoginModal());await s.page.waitForFunction(()=>HomeScene.current.running)}assert.equal(await s.page.evaluate(()=>HomeScene.current.id),id);assert.deepEqual(s.errors,[]);
 await s.page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));const destroyed=await s.page.evaluate(()=>HomeScene.current.inspect());assert.equal(destroyed.subscriptions,0);assert.equal(destroyed.raf,false);
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m3/step-012-controlled-results.json'),JSON.stringify({scope:'Actual shared login modal and actual VoiceEntry.begin/close on desktop; controlled terminal DOM states, no microphone/network/audio call acceptance',pass:true,id,destroyed},null,2)+'\n');console.log('PASS actual panel visibility/combination/cleanup; real audio pending')
 }finally{await s.close()}})().catch(e=>{console.error(e);process.exitCode=1});
