const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const results=[];for(const token of [false,true]){const s=await setup({token});try{
 await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));await s.page.goto(s.origin+'/pages/index.html');await s.page.waitForFunction(()=>HomeScene.current.running);
 assert.equal(await s.page.getByRole('button',{name:'轻触林小梦'}).count(),1,'Local character action must be accessible');
 await s.page.waitForFunction(()=>getHomeDataController().inspect().batches===0);const count=s.apiRequests.length,url=s.page.url(),hit=s.page.getByRole('button',{name:'轻触林小梦'});
 const before=await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount);await hit.click();await s.page.waitForFunction(n=>HomeScene.motion.inspect().responseCount===n+1,before);await s.page.evaluate(()=>{for(let i=0;i<30;i++)document.querySelector('.home-scene-hit').click()});assert.equal(await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount),before+1);
 await s.page.waitForTimeout(2400);await hit.focus();await s.page.keyboard.press('Enter');await s.page.waitForTimeout(2400);await s.page.keyboard.press('Space');assert.equal(await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount),before+3);assert.equal(s.apiRequests.length,count);assert.equal(s.page.url(),url);
 await s.page.evaluate(()=>HomeScene.current.pause('test-panel'));const stopped=await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount);await s.page.evaluate(()=>document.querySelector('.home-scene-hit').click());assert.equal(await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount),stopped);await s.page.evaluate(()=>HomeScene.current.pause('test-panel',false));await s.page.emulateMedia({reducedMotion:'reduce'});await s.page.evaluate(()=>document.querySelector('.home-scene-hit').click());assert.equal(await s.page.evaluate(()=>HomeScene.motion.inspect().responseCount),stopped);
 await s.page.locator('.home-quick-btn').first().click();if(!token)await s.page.waitForSelector('#auth-login-modal.is-open');assert.deepEqual(s.errors,[]);results.push({case:(token?'authenticated':'visitor')+' click, Enter/Space, merged repeat, paused suppression, network/navigation unchanged',pass:true});
 }finally{await s.close()}}
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m3/step-009-results.json'),JSON.stringify({scope:'Actual page desktop mouse/keyboard and controlled reduced motion; native mobile gestures pending M4',results},null,2)+'\n');console.log('PASS character local response and input priority')
})().catch(e=>{console.error(e);process.exitCode=1});
