const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const results=[];let s=await setup();try{
 await s.page.addInitScript(()=>sessionStorage.setItem('lxm_home_loader_done','1'));await s.page.goto(s.origin+'/pages/index.html');assert.equal(await s.page.evaluate(()=>!!HomeScene.quality),true,'Quality sampler must be owned by the scene');await s.page.waitForTimeout(1500);const measured=await s.page.evaluate(()=>({quality:HomeScene.quality.inspect(),motion:HomeScene.motion.inspect()}));assert.equal(measured.quality.calibrated,false);assert.equal(measured.quality.level,0);assert.ok(measured.motion.canvas.dpr<=1.5);assert.ok(measured.quality.metrics.frames>30);results.push({case:'uncalibrated desktop metrics are collected without invented Q201 parameters',pass:true,measured})
 }finally{await s.close()}
 s=await setup({token:true});try{
 await s.page.addInitScript(()=>{
  sessionStorage.setItem('lxm_home_loader_done','1');window.HomeSceneCalibration={pixelBudget:200000,windowMs:300,minimumFps:30,source:'controlled-desktop-test-only'};
  if(!sessionStorage.getItem('__quality_slow_fixture')){sessionStorage.setItem('__quality_slow_fixture','1');window.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),80);window.cancelAnimationFrame=clearTimeout}
 });
 await s.page.goto(s.origin+'/pages/index.html',{waitUntil:'domcontentloaded'});await s.page.waitForFunction(()=>HomeScene.quality.inspect().level>=1);const first=await s.page.evaluate(()=>({q:HomeScene.quality.inspect(),m:HomeScene.motion.inspect()}));assert.equal(first.q.level,1);assert.ok(first.m.canvas.pixels<=200000);
 await s.page.waitForFunction(()=>HomeScene.quality.inspect().level>=2);const second=await s.page.evaluate(()=>HomeScene.quality.inspect());assert.equal(second.level,2);assert.equal(await s.page.locator('.home-scene-hair-side').evaluate(e=>Number(e.style.opacity)),0);
 await s.page.waitForFunction(()=>HomeScene.quality.inspect().level===3);assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);
 await s.page.evaluate(()=>{const c=HomeScene.current;c.pause('test-hidden');c.pause('test-hidden',false);c.setMotionEnabled(false);c.setMotionEnabled(true);window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))});assert.equal(await s.page.evaluate(()=>HomeScene.quality.inspect().level),3);assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);
 await s.page.reload({waitUntil:'domcontentloaded'});assert.equal(await s.page.evaluate(()=>HomeScene.quality.inspect().level),0);await s.page.evaluate(()=>HomeScene.current.setMotionEnabled(false));await s.page.reload({waitUntil:'domcontentloaded'});assert.equal(await s.page.evaluate(()=>HomeScene.current.running),false);assert.equal(await s.page.evaluate(()=>HomeScene.current.motionEnabled),false);assert.deepEqual(s.errors,[]);results.push({case:'controlled calibration caps pixels and drops environment→hair→static; same instance retains, new page reassesses preference',pass:true,first,second})
 }finally{await s.close()}
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m3/step-013-controlled-results.json'),JSON.stringify({scope:'Desktop measurements and deliberately controlled 200000px/300ms/30fps calibration. These parameters are NOT production/Q201 selections.',results},null,2)+'\n');console.log('PASS local quality logic; actual Q201 pixel budget/window/threshold pending')
})().catch(e=>{console.error(e);process.exitCode=1});
