const assert=require('node:assert/strict'),fs=require('node:fs');const {setup,artifact}=require('./home_browser_helpers.cjs');
(async()=>{const s=await setup({nativeBfcache:true});try{
 await s.page.addInitScript(()=>{sessionStorage.setItem('lxm_home_loader_done','1');window.fixturePageIdentity=Date.now()+':'+Math.random();window.fixturePageShows=[];window.addEventListener('pageshow',e=>window.fixturePageShows.push(e.persisted))});
 await s.page.goto(s.origin+'/pages/index.html');await s.page.waitForFunction(()=>HomeScene.current.running);await s.page.waitForFunction(()=>HomeScene.motion.inspect().loaded.length===5);await s.page.waitForFunction(()=>getHomeDataController().inspect().batches===0);
 await s.page.evaluate(()=>{HomeScene.quality.configure({pixelBudget:200000,windowMs:300,minimumFps:30,source:'controlled-native-bfcache-test-only'});window.requestAnimationFrame=fn=>setTimeout(()=>fn(performance.now()),80);window.cancelAnimationFrame=clearTimeout});await s.page.waitForFunction(()=>HomeScene.quality.inspect().level>=1);await s.page.evaluate(()=>HomeScene.current.pause('test-hold-quality'));
 const before=await s.page.evaluate(()=>({identity:window.fixturePageIdentity,scene:HomeScene.current.inspect(),quality:HomeScene.quality.inspect().level}));await s.page.goto(s.origin+'/pages/login.html');await s.page.goBack({waitUntil:'commit'});await s.page.waitForFunction(()=>window.HomeScene&&window.fixturePageShows.includes(true));
 const after=await s.page.evaluate(()=>({identity:window.fixturePageIdentity,shows:window.fixturePageShows,scene:HomeScene.current.inspect(),quality:HomeScene.quality.inspect().level}));assert.equal(after.identity,before.identity,'Native back must restore original page instance');assert.ok(after.shows.includes(true),'Actual pageshow persisted must be true');assert.equal(after.scene.id,before.scene.id);assert.ok(after.scene.time-before.scene.time<1000);assert.equal(after.quality,before.quality);await s.page.evaluate(()=>HomeScene.current.pause('test-hold-quality',false));assert.deepEqual(s.errors,[]);
 fs.writeFileSync(artifact('docs/design/home-redesign/execution/evidence/home-m3/native-bfcache-results.json'),JSON.stringify({scope:'Real desktop Chrome native forward/back cache with Playwright cache-disabling launch flag removed; actual navigation to login and browser back',pass:true,before,after},null,2)+'\n');console.log('PASS native Chrome bfcache preserved the original scene and clamped resume')
 }finally{await s.close()}})().catch(e=>{console.error(e);process.exitCode=1});
